from webbee.events import TurnSink


def test_turnsink_is_runtime_checkable():
    class Fake:
        def tool_start(self, tool, args): ...
        def tool_result(self, tool, ok, summary): ...
        def ask_consent(self, app_id, tool, args): return "yes"
        def panel_release(self, panel_url, summary): ...
        def progress(self, text): ...
        def usage(self, tokens, cost_usd): ...
        def plan_blocked(self, tool): ...
        def user_echo(self, text): ...
    assert isinstance(Fake(), TurnSink)


def test_turnsink_requires_user_echo():
    class Missing:
        def tool_start(self, tool, args): ...
        def tool_result(self, tool, ok, summary): ...
        def ask_consent(self, app_id, tool, args): return "y"
        def panel_release(self, panel_url, summary): ...
        def progress(self, text): ...
        def usage(self, tokens, cost_usd): ...
        def plan_blocked(self, tool): ...
        # no user_echo
    assert not isinstance(Missing(), TurnSink)


def test_richsink_still_satisfies_turnsink_with_plan_blocked():
    from webbee.render import RichSink
    from rich.console import Console
    s = RichSink(console=Console(record=True), live_enabled=False,
                 input_fn=lambda p: "", clock=lambda: 0.0)
    assert isinstance(s, TurnSink)
    assert hasattr(s, "plan_blocked")
