from webbee.events import TurnSink


def test_turnsink_is_runtime_checkable():
    class Fake:
        def tool_start(self, tool, args): ...
        def tool_result(self, tool, ok, summary): ...
        def ask_consent(self, app_id, tool, args): return "yes"
        def panel_release(self, panel_url, summary): ...
        def progress(self, text): ...
        def usage(self, tokens, cost_usd): ...
    assert isinstance(Fake(), TurnSink)
