from typing import Protocol, runtime_checkable


@runtime_checkable
class TurnSink(Protocol):
    """Everything a running coding turn tells the UI. The renderer (render.py)
    implements this with Rich; tests implement it with a recording fake.
    session.py imports ONLY this — never Rich — so the SSE loop stays testable."""

    def tool_start(self, tool: str, args: dict) -> None: ...
    def tool_result(self, tool: str, ok: bool, summary: str) -> None: ...
    def ask_consent(self, app_id: str, tool: str, args: dict) -> str: ...
    def panel_release(self, panel_url: str, summary: str) -> None: ...
    def progress(self, text: str) -> None: ...
    def usage(self, tokens: int, cost_usd: float) -> None: ...
    def plan_blocked(self, tool: str) -> None: ...
    def user_echo(self, text: str) -> None: ...
